### ISSUE TITLE
Setup in docker-compose, container won't go up

### ISSUE THREAD

**Issue by Shakmir** [dada513/Discordio#10]
Not sure if I'm missing something or doing something wrong, but I tried to set the bot up in docker-compose since that's how I keep my containers running, but discordio won't go up.
This is how I set it up in my docker-compose.yml:
```
  discordio:
    container_name: discordio
    image: dada513/discordio
    volumes:
      - /opt/appdata/discordio:/dio
    restart: unless-stopped
```

This is what I get in my logs:
```
 internal/modules/cjs/loader.js:834
  throw err;
  ^
Error: Cannot find module 'esm'
Require stack:
- /dio/launcher.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/dio/launcher.js:2:11)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/dio/launcher.js' ]
}
```

Sorry in advance if I'm doing something very obvious wrong, I'm still a Docker noob.
